[package]
name = "wallet-gen"
version = "0.2.0"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]

[dependencies]
base58 = "*"
either = "1"
openssl = "0.10"
serde = { version = "1", optional = true, features = ["derive"] }
tiny-keccak = "1"
