[package]
name = "wallet-gen"
version = "0.3.2"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]

[dependencies]
arrayvec = "0.4"
base58 = "0.1"
digest = "0.7"
either = "1"
lazy_static = "1"
openssl = "0.10"
serde = { version = "1", optional = true, features = ["derive"] }
tiny-keccak = "1"
